# Generated by Django 5.0.6 on 2024-07-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiraautomatica',
            name='ativos',
        ),
        migrations.RemoveField(
            model_name='carteiramanual',
            name='ativos',
        ),
        migrations.DeleteModel(
            name='Benchmark',
        ),
        migrations.RemoveField(
            model_name='carteiraautomatica',
            name='indicadores',
        ),
        migrations.RemoveField(
            model_name='simulacaoautomatica',
            name='carteira_automatica',
        ),
        migrations.RemoveField(
            model_name='carteiramanual',
            name='indicadores',
        ),
        migrations.RemoveField(
            model_name='simulacaomanual',
            name='carteira_manual',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='simulacao_automatica',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='simulacao_manual',
        ),
        migrations.DeleteModel(
            name='Ativo',
        ),
        migrations.DeleteModel(
            name='CarteiraAutomatica',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='CarteiraManual',
        ),
        migrations.DeleteModel(
            name='SimulacaoAutomatica',
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.DeleteModel(
            name='SimulacaoManual',
        ),
    ]
