# Generated by Django 5.0.6 on 2024-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaoautomatica',
            name='tipo',
            field=models.CharField(default='automatica', max_length=10),
            preserve_default=False,
        ),
    ]
