# Generated by Django 5.0.6 on 2024-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0007_alter_ativo_nome_alter_ativo_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='simulacao',
        ),
        migrations.AddField(
            model_name='historico',
            name='simulacoes',
            field=models.ManyToManyField(to='simulador.simulacaoautomatica'),
        ),
    ]
