# Generated by Django 5.0.6 on 2024-10-01 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0009_ativo_data_lancamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_em_dinheiro', models.FloatField()),
                ('valor_ativos', models.FloatField()),
                ('moeda_base', models.CharField(max_length=10)),
                ('ativos', models.ManyToManyField(to='simulador.ativo')),
                ('indicadores', models.ManyToManyField(to='simulador.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('mes_atual', models.DateTimeField()),
                ('carteira_manual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulador.carteiramanual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
