# Generated by Django 5.0.6 on 2024-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_carteiramanual_simulacaomanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaomanual',
            name='inflacao_total',
            field=models.JSONField(default=dict),
        ),
    ]
