# Generated by Django 5.0.6 on 2024-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0012_remove_historico_simulacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacaoautomatica',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='simulacaomanual',
            name='tipo',
        ),
        migrations.AddField(
            model_name='simulacaomanual',
            name='historico_valor_total',
            field=models.JSONField(default=list),
        ),
    ]
