# Generated by Django 5.0.6 on 2024-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0013_remove_simulacaoautomatica_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiraautomatica',
            name='indicadores',
        ),
        migrations.RemoveField(
            model_name='carteiramanual',
            name='indicadores',
        ),
        migrations.AddField(
            model_name='ativo',
            name='ultimo_preco_convertido',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
    ]
